version: "3"
services:
  osai_backend:
    container_name: osai_backend
    build:
        context: ./
        dockerfile: dockerfile.osai_backend
    image: osai_backend:latest
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      MYSQL_DB_HOST: host.docker.internal
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
