version: "3"
services:
  backend_applicare:
    container_name: backend_applicare
    build:
        context: ./
        dockerfile: dockerfile.backend
    image: backend_applicare:latest
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      MYSQL_DB_HOST: host.docker.internal
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MONGO_CONNECTION_STRING: mongodb://host.docker.internal:27017
